# -*- coding: utf-8 -*-
# One-off converter: Realbyte "Pengelola Keuangan" .xlsx export -> normalized
# JSON the Kanal app loads as its real dataset (src/data/realbyteTransactions.json).
# Re-run whenever the user drops in a fresh export.
#
#   python kanal/scripts/convert-realbyte.py "Pengelola Keuangan_29-06-26.xlsx"

import json
import re
import sys
import unicodedata
from datetime import datetime
from pathlib import Path

import warnings
warnings.filterwarnings("ignore")
from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]  # kanal/
DEFAULT_SRC = ROOT.parent / "Pengelola Keuangan_29-06-26.xlsx"
OUT = ROOT / "src" / "data" / "realbyteTransactions.json"
OUT_TS = ROOT / "src" / "data" / "realbyteData.ts"

TYPE_MAP = {
    "Pengeluaran": "keluar",
    "Pendapatan": "masuk",
    "Transfer keluar": "pindah",
    "Transfer masuk": "pindah-masuk",  # collapsed below; kept distinct for direction
}

EMOJI_RE = re.compile(
    "[" "\U0001F000-\U0001FAFF" "\U00002600-\U000027BF" "\U0001F1E6-\U0001F1FF"
    "\U00002190-\U000021FF" "\U00002B00-\U00002BFF" "️" "]",
    flags=re.UNICODE,
)


def clean(s):
    if s is None:
        return ""
    return EMOJI_RE.sub("", str(s)).strip()


def to_iso(v):
    if isinstance(v, datetime):
        return v.replace(microsecond=0).isoformat()
    # fallback: try parse string
    s = str(v).split(".")[0]
    return s.replace(" ", "T")


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    wb = load_workbook(src, data_only=True)
    ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    header = [clean(c) for c in rows[0]]
    # "Aset" appears twice (account name + a numeric repeat); keep the first.
    idx = {}
    for i, h in enumerate(header):
        if h not in idx:
            idx[h] = i

    def col(row, name):
        i = idx.get(name)
        return row[i] if i is not None and i < len(row) else None

    out = []
    accounts, categories, types_seen = {}, {}, {}
    skipped = 0

    for r in rows[1:]:
        if r is None or all(c is None for c in r):
            continue
        raw_type = (col(r, "Pendapatan/Pengeluaran") or "").strip()
        kind = TYPE_MAP.get(raw_type)
        types_seen[raw_type] = types_seen.get(raw_type, 0) + 1
        if kind is None:
            skipped += 1
            continue

        amount_raw = col(r, "IDR")
        if amount_raw is None:
            amount_raw = col(r, "Total")
        try:
            amount = int(round(float(amount_raw)))
        except (TypeError, ValueError):
            skipped += 1
            continue

        account = (col(r, "Aset") or "").strip()
        kategori = clean(col(r, "Kategori"))
        catatan = (col(r, "Catatan") or "").strip()
        deskripsi = (col(r, "Deskripsi") or "").strip()
        ts = to_iso(col(r, "Tanggal"))

        is_transfer = kind in ("pindah", "pindah-masuk")
        tx = {
            "type": "pindah" if is_transfer else kind,
            "amount": amount,
            "account": account,
            "timestamp": ts,
            "label": catatan or deskripsi or (kategori if not is_transfer else "Transfer"),
        }
        if is_transfer:
            # For transfers the Kategori column holds the counterpart account.
            tx["toAccount"] = kategori
        else:
            tx["category"] = kategori
            categories[kategori] = categories.get(kategori, 0) + 1
        if deskripsi and deskripsi != tx["label"]:
            tx["note"] = deskripsi

        accounts[account] = accounts.get(account, 0) + 1
        out.append(tx)

    # chronological ascending
    out.sort(key=lambda t: t["timestamp"])
    for i, t in enumerate(out):
        t["id"] = f"rb{i:04d}"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=0), encoding="utf-8")

    # Typed TS module the app imports. The payload is embedded as a string and
    # JSON.parse'd at runtime so TypeScript never infers a giant literal type
    # (keeps tsc fast). Auto-generated — do not hand-edit.
    compact = json.dumps(out, ensure_ascii=False, separators=(",", ":"))
    js_literal = json.dumps(compact)  # safe JS/TS string literal (escaped)
    ts = (
        "// AUTO-GENERATED by scripts/convert-realbyte.py — do not edit.\n"
        "// Source: Realbyte 'Pengelola Keuangan' xlsx export.\n\n"
        "export interface RawTx {\n"
        "  id: string\n"
        "  type: 'masuk' | 'keluar' | 'pindah'\n"
        "  amount: number\n"
        "  account: string\n"
        "  category?: string\n"
        "  toAccount?: string\n"
        "  label: string\n"
        "  note?: string\n"
        "  timestamp: string\n"
        "}\n\n"
        f"export const REALBYTE_RAW: RawTx[] = JSON.parse(\n  {js_literal},\n)\n"
    )
    OUT_TS.write_text(ts, encoding="utf-8")

    dates = [t["timestamp"][:10] for t in out]
    print("WROTE:", OUT, "->", len(out), "transactions")
    print("DATE RANGE:", min(dates), "->", max(dates))
    print("TYPES SEEN:", types_seen, "| skipped:", skipped)
    print("ACCOUNTS:", dict(sorted(accounts.items(), key=lambda x: -x[1])))
    print("CATEGORIES:", dict(sorted(categories.items(), key=lambda x: -x[1])))


if __name__ == "__main__":
    main()
